SV-925 Approvals Standard Cache
SkillsFundingAgency/das-courses-api pull request #101
Opened 2021-07-30 14:55 UTC by CodeWolf86

2021-08-03 14:30 UTC, ben1stone requested changes

2021-08-11 15:57 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Data/Configuration/Standard.cs
> +            builder.Property(x => x.Version).HasColumnName("Version").HasColumnType("varchar").HasMaxLength(50);
Yep it should. Changed

2021-08-11 15:57 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Data/Extensions/StandardFilterExtension.cs
>                          var standardsByIfateReferenceNumber = standards.GroupBy(s => s.IfateReferenceNumber).Select(c => c.OrderByDescending(x => x.Version).FirstOrDefault());
Yes for consistency. Changed.

2021-08-11 15:58 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Domain/Extensions/ToStandardVersionIdExtension.cs
> +        public static string ToStandardVersionId(this string ifateReferenceNumber, string version)
Yep have renamed it.

2021-08-12 08:03 UTC, ben1stone approved these changes

2021-08-12 12:19 UTC, StuartReeve102 commented on src/SFA.DAS.Courses.Domain/Courses/Standard.cs
> +        public string Version { get; set; }
This refers to multiple classes, where you have added a string Version and interger VersionMajor and VersionMinor, properties, shouldn't the string Version property be a calculated property based on VersionMajor and VersionMinor?

2021-08-12 12:24 UTC, StuartReeve102 requested changes

2021-08-12 12:24 UTC, StuartReeve102 commented on src/SFA.DAS.Courses.Domain/Courses/Standard.cs
> +        public string Version { get; set; }
This refers to multiple classes, where you have added a string Version and interger VersionMajor and VersionMinor, properties, shouldn't the string Version property be a calculated property based on VersionMajor and VersionMinor?

2021-08-12 13:07 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Domain/Courses/Standard.cs
> +        public string Version { get; set; }
Given the data from Ifate comes in as a string, it seemed best to store that as is so we hold the original value. The VersionMajor VersionMinor is the calculated aspect from splitting the original field. The sole purpose of the split was purely for ordering purposes at the database level. It is a little bit duplicated but it seemed the simplest option.

2021-08-12 14:09 UTC, StuartReeve102 approved these changes

2021-09-06 07:23 UTC, merged