QF-1730-Treat-Ofqual-is-the-intended-EQA-provider-as-Ofqual
SkillsFundingAgency/das-courses-api pull request #137
Opened 2024-02-08 10:35 UTC by Jordan-fujitsu

2024-02-08 10:54 UTC, ChrisJWoodcock requested changes
This needs some tests to see that the replacement has been made

2024-02-08 10:54 UTC, ChrisJWoodcock commented on src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs
> +        private void  SetEqaProviderName(List<Domain.ImportTypes.Standard> standards)
Would be better called UpdateEqaProviderName to match the other update call which is done above it

2024-02-08 10:55 UTC, ChrisJWoodcock commented on src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs
> +        private void  SetEqaProviderName(List<Domain.ImportTypes.Standard> standards)
Oh and remove the double space

2024-02-08 11:15 UTC, Jordan-fujitsu commented on src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs
> +        private void  SetEqaProviderName(List<Domain.ImportTypes.Standard> standards)
Renamed method and fixed spacing

2024-02-08 13:12 UTC, Jordan-fujitsu commented
@ChrisJWoodcock added unit test` Then_EqaProviderName_Is_Updated_If_Ofqual_Is_Intended` which checks eqa provider name is gets updated to Ofqual when originally set to "Ofqual is the intended EQA provider"

2024-02-08 17:14 UTC, ChrisJWoodcock submitted a review, later dismissed

2024-02-12 11:16 UTC, ChrisJWoodcock approved these changes

2024-02-19 11:05 UTC, merged