SV-484 new options endpoint
SkillsFundingAgency/das-courses-api pull request #72
Opened 2021-02-25 17:40 UTC by ben1stone

2021-02-25 18:20 UTC, DevenKShah requested changes
Looks good, just need to remove total fields.

2021-02-25 18:20 UTC, DevenKShah commented on src/SFA.DAS.Courses.Api.AcceptanceTests/Infrastructure/DbUtilities.cs
> +                    Options = new List<string>
May be add options to all different status and check that only standard in "Approved for delivery" and "Retired" are coming back.

2021-02-25 18:20 UTC, DevenKShah commented on src/SFA.DAS.Courses.Api.AcceptanceTests/Steps/OptionsSteps.cs
> +                .Excluding(c => c.ApprenticeshipFunding)
There is option to say `ExcludingMissingMembers` but I would just not use fluent extension here, instead just check fields explicitly

2021-02-25 18:20 UTC, DevenKShah commented on src/SFA.DAS.Courses.Api.UnitTests/Controllers/Standards/StandardToGetStandardOptionsResponseOptions.cs
> +                .Excluding(c => c.SearchScore)
There is option to say `ExcludingMissingMembers` but I would just not use fluent extension here, instead just check fields explicitly

2021-02-25 18:20 UTC, DevenKShah commented on src/SFA.DAS.Courses.Api.UnitTests/Controllers/Standards/StandardToGetStandardOptionsResponseOptions.cs
> +    public static class StandardToGetStandardOptionsResponseOptions
may be `StandardToGetStandardOptionsResponseEquivalencyAsssertionOptions`.
I know this is longer than the longest name in Wales `Llanfair­pwllgwyngyll­gogery­chwyrn­drobwll­llan­tysilio­gogo­goch station`

2021-02-26 08:59 UTC, CodeWolf86 requested changes

2021-02-26 08:59 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Api/ApiResponses/GetStandardOptionsListResponse.cs
> +        public int Total { get; set; }
Total was useful in the original get for standards as it has filters and search parameters. In the get options case it just returns the data set of active options so can be simplified

2021-02-26 08:59 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Api/Controllers/OptionsController.cs
> +                _logger.LogError(e, "Error attempting to get list of standards");
Possible Copy and Paste gotcha? 😁

2021-02-26 08:59 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Api/Controllers/OptionsController.cs
> +                    Keyword = string.Empty,
Should be able to get away with just specifying Filter = Active, the rest shouldn't matter and don't need to be set. It's an argument of Explicit vs Implicit but I'm happy with either

2021-02-26 08:59 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Api/ApiResponses/GetStandardOptionsResponse.cs
> +        public static implicit operator GetStandardOptionsResponse(Standard source)
Are you happy with the implicit operator and how it works?

2021-02-26 08:59 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Api.UnitTests/Controllers/Standards/StandardToGetStandardOptionsResponseOptions.cs
> +                .Excluding(c => c.SearchScore)
This does feel a bit overkill 😄  I understand what you've done, in that get standards and it's equivalency works because it returns so many fields. In this instance, rather than equivalence I'd assert on explicit fields as Deven mentioned as there are only four fields.

2021-02-26 08:59 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Api.UnitTests/Controllers/Standards/StandardToGetStandardOptionsResponseOptions.cs
> +    public static class StandardToGetStandardOptionsResponseOptions
Did you type that from memory ? 😛

2021-02-26 09:12 UTC, DevenKShah commented on src/SFA.DAS.Courses.Api.UnitTests/Controllers/Standards/StandardToGetStandardOptionsResponseOptions.cs
> +    public static class StandardToGetStandardOptionsResponseOptions
@CodeWolf86 I can't spell English words properly, worst thing is I will not be able to tell I have spelling errors here 😆

2021-02-26 11:27 UTC, ben1stone commented on src/SFA.DAS.Courses.Api/Controllers/OptionsController.cs
> +                _logger.LogError(e, "Error attempting to get list of standards");
yep, fixed

2021-02-26 18:42 UTC, CodeWolf86 approved these changes

2021-03-04 18:41 UTC, closed without merging