SV-483 Rename MaxFunding and TypicalDuration
SkillsFundingAgency/das-courses-api pull request #80
Opened 2021-03-09 14:40 UTC by ben1stone

2021-03-09 14:58 UTC, DevenKShah approved these changes
Looks good, only the refactor log is questionable.

2021-03-09 14:58 UTC, DevenKShah commented on src/SFA.DAS.Courses.Database/SFA.DAS.Courses.Database.refactorlog
> +﻿<?xml version="1.0" encoding="utf-8"?>
Do we need this refactor log? I guess we will just create a script to drop and recreate the table.

2021-03-09 15:39 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Database/SFA.DAS.Courses.Database.refactorlog
> +﻿<?xml version="1.0" encoding="utf-8"?>
The Refactor Log is created due to the creation of the __Refactor table on publish of the DACPAC. This was due to the renaming change of the columns and is the standard way the project operates.

If we don't like the __Refactor table / the Refactor log, the alternative is we create a pre-deployment script and just rename the columns before the publish? so that the schema is correct but if the original names exist we rename before hand

2021-03-10 09:49 UTC, DevenKShah commented on src/SFA.DAS.Courses.Database/SFA.DAS.Courses.Database.refactorlog
> +﻿<?xml version="1.0" encoding="utf-8"?>
Are we going to deploy DB changes using DACPAC going forward?

2021-03-10 09:57 UTC, CodeWolf86 commented on src/SFA.DAS.Courses.Database/SFA.DAS.Courses.Database.refactorlog
> +﻿<?xml version="1.0" encoding="utf-8"?>
The DACPAC is the default way we deploy changes and the way we should be deploying them. When fields were added as part of Standards Versioning that's how they were introduced to the DB. The problem we had in the last run was the change of the primary key and renaming of columns causing the DACPAC to fail. When I inquired with DevOps they said they can change the release pipeline for the DACPAC to drop and recreate the database in that instance but preferred a script as it was less destructive.

In hindsight, Alans suggestion of a pre-deployment script to make some tabular changes before deploy may have been the best bet but we were too far in to hold up the release anymore so I'm looking at this one with a fresh pair of eyes.

DACPAC does work in this instance, hence why it used the refactor log, this was so it doesn't just drop the columns and add new ones when it is in fact a re-name. ( means we don't have to re-run the import )

So this time around we can either stick with the above refactor log, or move to a pre-deployment / post deployment script mechanism which is easily added to the database project ( it's add item -> scripts at the project ) and it creates a pre-deploy script. It runs this every time, so it could just simply be a 

```If Column MaxFunding Exists -> Rename ```

Which would then negate the entire refactor, and setup the db for the DACPAC to run ( would need testing though ) but would remove the refactor log and refactor table.

2021-03-10 10:18 UTC, CodeWolf86 requested changes
Hi @ben1stone Just as a trial. Could you try changing it using a Pre-Deploy script to see what that looks like? Then can make a call on Refactor vs Pre-Deploy

2021-03-11 16:37 UTC, DevenKShah approved these changes

2021-03-11 17:14 UTC, merged